//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARMzalogApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARMzalogApp.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт.
        /// </summary>
        internal static string txtAccountTab {
            get {
                return ResourceManager.GetString("txtAccountTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деятельность № 1.
        /// </summary>
        internal static string txtActivity1 {
            get {
                return ResourceManager.GetString("txtActivity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деятельность № 2.
        /// </summary>
        internal static string txtActivity2 {
            get {
                return ResourceManager.GetString("txtActivity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деятельность № 3.
        /// </summary>
        internal static string txtActivity3 {
            get {
                return ResourceManager.GetString("txtActivity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупка.
        /// </summary>
        internal static string txtBuy {
            get {
                return ResourceManager.GetString("txtBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать и отправить фото из галереи.
        /// </summary>
        internal static string txtChooseAndSendPhotoFromGallery {
            get {
                return ResourceManager.GetString("txtChooseAndSendPhotoFromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык приложения:.
        /// </summary>
        internal static string txtChooseAppLanguage {
            get {
                return ResourceManager.GetString("txtChooseAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите размер шрифта.
        /// </summary>
        internal static string txtChooseFontSize {
            get {
                return ResourceManager.GetString("txtChooseFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото клиента.
        /// </summary>
        internal static string txtClientPhoto {
            get {
                return ResourceManager.GetString("txtClientPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата заявки.
        /// </summary>
        internal static string txtDateOfZayavka {
            get {
                return ResourceManager.GetString("txtDateOfZayavka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите позиционный номер/Enter the code.
        /// </summary>
        internal static string txtEnterPositionNumber {
            get {
                return ResourceManager.GetString("txtEnterPositionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите чтобы продолжить.
        /// </summary>
        internal static string txtEnterToContinue {
            get {
                return ResourceManager.GetString("txtEnterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти/Search.
        /// </summary>
        internal static string txtFind {
            get {
                return ResourceManager.GetString("txtFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ф.И.О..
        /// </summary>
        internal static string txtFIO {
            get {
                return ResourceManager.GetString("txtFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсы валют.
        /// </summary>
        internal static string txtKursValuta {
            get {
                return ResourceManager.GetString("txtKursValuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсы валют на дату.
        /// </summary>
        internal static string txtKursValutForCurrentDate {
            get {
                return ResourceManager.GetString("txtKursValutForCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт ЗАГРУЗКА. Пожайлуста, ПОДОЖДИТЕ.
        /// </summary>
        internal static string txtLoadingPleaseWait {
            get {
                return ResourceManager.GetString("txtLoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string txtLogIn {
            get {
                return ResourceManager.GetString("txtLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string txtLogout {
            get {
                return ResourceManager.GetString("txtLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        internal static string txtMainTab {
            get {
                return ResourceManager.GetString("txtMainTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        internal static string txtOther {
            get {
                return ResourceManager.GetString("txtOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото с места жительства.
        /// </summary>
        internal static string txtPhotoResidence {
            get {
                return ResourceManager.GetString("txtPhotoResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото деятельностей.
        /// </summary>
        internal static string txtPhotosActivity {
            get {
                return ResourceManager.GetString("txtPhotosActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото с первой месты деятельности.
        /// </summary>
        internal static string txtPhotosFirstActivity {
            get {
                return ResourceManager.GetString("txtPhotosFirstActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото со второй месты деятельности.
        /// </summary>
        internal static string txtPhotosSecondActivity {
            get {
                return ResourceManager.GetString("txtPhotosSecondActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото с третьей месты деятельности.
        /// </summary>
        internal static string txtPhotosThirdActivity {
            get {
                return ResourceManager.GetString("txtPhotosThirdActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить выбранные фотографии.
        /// </summary>
        internal static string txtSaveChoosePhoto {
            get {
                return ResourceManager.GetString("txtSaveChoosePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажа.
        /// </summary>
        internal static string txtSold {
            get {
                return ResourceManager.GetString("txtSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string txtSumma {
            get {
                return ResourceManager.GetString("txtSumma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать фото.
        /// </summary>
        internal static string txtTakePhoto {
            get {
                return ResourceManager.GetString("txtTakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать фото и сохранить в галерею.
        /// </summary>
        internal static string txtTakePhotoAndSaveInGallery {
            get {
                return ResourceManager.GetString("txtTakePhotoAndSaveInGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать фото и отправить.
        /// </summary>
        internal static string txtTakePhotoAndSend {
            get {
                return ResourceManager.GetString("txtTakePhotoAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать фото паспорта с обратной стороны.
        /// </summary>
        internal static string txtTakePhotoPassportBackSide {
            get {
                return ResourceManager.GetString("txtTakePhotoPassportBackSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать фото паспорта с лицевой стороны.
        /// </summary>
        internal static string txtTakePhotoPassportFrontSide {
            get {
                return ResourceManager.GetString("txtTakePhotoPassportFrontSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать фото клиента с паспортом в руке.
        /// </summary>
        internal static string txtTakePhotoWithPassportInHand {
            get {
                return ResourceManager.GetString("txtTakePhotoWithPassportInHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сделать фото залога и отправить.
        /// </summary>
        internal static string txtTakePhotoZalog {
            get {
                return ResourceManager.GetString("txtTakePhotoZalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транспорт.
        /// </summary>
        internal static string txtTransport {
            get {
                return ResourceManager.GetString("txtTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип залога.
        /// </summary>
        internal static string txtTypeOfZalog {
            get {
                return ResourceManager.GetString("txtTypeOfZalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        internal static string txtWelcome {
            get {
                return ResourceManager.GetString("txtWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото залога.
        /// </summary>
        internal static string txtZalog {
            get {
                return ResourceManager.GetString("txtZalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Земельный участок.
        /// </summary>
        internal static string txtZemelnyiUchastork {
            get {
                return ResourceManager.GetString("txtZemelnyiUchastork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жилая недвижимость.
        /// </summary>
        internal static string txtZhilayNedvizhimost {
            get {
                return ResourceManager.GetString("txtZhilayNedvizhimost", resourceCulture);
            }
        }
    }
}
